services:
  frontend:
    image: node:22
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    command: npx http-server -p 8080 --cors
    
  backend:
      image: node:22
      working_dir: /app
      ports: 
        - "3000:3000"
      environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASSWORD: 123
        DB_NAME: db_intro
      volumes:
        - ./backend/app:/app
        - /app/node_modules
      command: sh -c "npm install && exec npx nodemon app.js"
      depends_on:
        - db

  db:
    image: postgres:15
    container_name: base_tp_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db_intro
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./backend/app/db/init.sql:/docker-entrypoint-initdb.d/init.sql